# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
